version: '3'

services:

  finio-react:
    container_name: finio-react
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2001:3000"
    volumes:
        - ./:/app
    environment:
        - NODE_ENV = 'development'
        - DEBUG = 'True'
        - SECRET_KEY = "35235b36-ede5-4e00-865d-5dbd7a1944e2"



