version: '3.2'

services:

  finio-react:
    container_name: finio-react
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
        CHOKIDAR_USEPOLLING: "true"
        NODE_ENV: development
        DEBUG: "true"
        SECRET_KEY: "SECRET_KEY"
    ports:
      - "2001:3000"
    volumes:
        - ./:/app




